# Generated by Django 3.2.12 on 2022-02-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='name',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='max_num_purchases',
            field=models.IntegerField(default=10),
        ),
    ]
